### ISSUE TITLE
Should this kernel boot on a Jetson TX2?

### ISSUE THREAD

**Issue by dhess** [grate-driver/linux#1]
Hi, hopefully you don't mind if I post an issue/question here as I'm not sure where the project "lives," per se.

Is this kernel expected to work on a Jetson TX2 development board? I'm trying to get NixOS working on mine and I've had no luck with any kernel so far, including this one.

I can build the grate-driver kernel just fine on NixOS running on my Jetson TX1, and it works great there. It boots from the TX1's built-in eMMC, and then the NixOS root filesystem is mounted from an NVMe drive that's plugged into a PCIe riser board on the TX1. That configuration is very stable and has been working for awhile now under heavy loads.

However, the exact same filesystem won't boot on the TX2. I've copied the `/boot` fs from the TX1 eMMC to an SDHC card, and installed the NVMe drive/PCIe riser card on the TX2. Here is the boot log:

https://gist.github.com/dhess/d41a7c806a61e0b886a2cd0defed2c6a

I have also tried the "official" Tegra kernel from https://git.kernel.org/pub/scm/linux/kernel/git/tegra/linux.git on the TX2, and the results are effectively the same -- the TX2 can't find the root fs device.

Any ideas?

**Comment by kusma** [comment]
Grate is about GPU-enablement on Tegra 2/3/4, not Tegra K1 and later. So the grate-kernel is probably not the right one for your system.

Tegra TX1 development happens at linux-tegra@vger.kernel.org (and #tegra on freenode). Perhaps you should direct these questions there instead? You'll be more likely to reach someone with relevant experience there...

**Comment by dhess** [comment]
Ack, sorry, I could have sworn I saw Tegra 210 patches in this kernel. Sorry for the noise!
