### ISSUE TITLE
Lenovo ideatab: dt-schema warnings

### ISSUE THREAD

**Issue by okias** [grate-driver/linux#109]
@KaiJan57 

```
/home/runner/work/linux/linux/arch/arm/boot/dts/tegra30-lenovo-ideatab-a2109a.dt.yaml: pmic@3c: pinmux: Unevaluated properties are not allowed ('pin_gpio0', 'pin_gpio1', 'pin_gpio2', 'pin_gpio3', 'pin_gpio4', 'pin_gpio5', 'pin_gpio6', 'pin_gpio7' were unexpected)
	From schema: /home/runner/work/linux/linux/Documentation/devicetree/bindings/mfd/max77620.yaml
```

Bonus:
```
SPDX-License-Identifier: GPL-2.0
```
preferably specify if `GPL-2.0-only` or `-or-later`

**Comment by KaiJan57** [comment]
Today I found some time to look into this problem, but I am sorry to say that I have no idea how to fix it… This section's structure was pretty much directly taken from grouper, so I am puzzled that it is only this dts that causes problems. Also, I couldn't find `max77620.yaml` mentioned in the error message.

**Comment by okias** [comment]
oh, ok, that explains it, I didn't noticed it's not upstreamed yet. It's from Thierry and only in my `dt_bindings` branch.

https://github.com/okias/linux/commit/d408cd96c67f183f9e6c60781258a1f230202037

anyway, seems like `pin_gpio[0-9]` aren't defined in driver or binding, or can you verify?

**Comment by KaiJan57** [comment]
Very odd, the device tree does not contain anything like `pin_gpio` but much rather `gpio[0-9]`, for example:
https://github.com/grate-driver/linux/blob/25a51002123c3dcefa67df65c13a5152fc0358ce/arch/arm/boot/dts/tegra30-lenovo-ideatab-a2109a.dts#L1119-L1121

as in grouper; refer to:
https://github.com/grate-driver/linux/blob/25a51002123c3dcefa67df65c13a5152fc0358ce/arch/arm/boot/dts/tegra30-asus-nexus7-grouper-maxim-pmic.dtsi#L25-L27

Also, your `yaml` specification seems to accept these expressions (if I'm not misunderstanding [these lines](https://github.com/okias/linux/blob/d408cd96c67f183f9e6c60781258a1f230202037/Documentation/devicetree/bindings/mfd/max77620.yaml#L317)) as I would expect them to be correct, as I have looked into the source code of the ic's driver to determine the correct parameters, matching the downstream kernel settings.
