### ISSUE TITLE
CI for builds with musl

### ISSUE THREAD

**Issue by antonialoytorrens** [grate-driver/linux#118]
To test new kernels from here, I have to compile them every time on my computer before testing anything. My computer is not fast, and it may take hours to compile and test a single kernel build.

To work around that, I'm using a custom version of Debian on my TF101.
Nevertheless, for easier installation, automation and deployment, PostmarketOS is far better and more recommended for these devices.

Is it possible to add an extra CI implementation with musl (from Alpine Linux latest)?

**Comment by okias** [comment]
I'm pretty sure it's not about the Alpine.

First, the generated kernel (which we currently build) is libc agnostic, so you can run it on Debian, pmOS, or any distro you can find.

Second, would be nice to have something like pre-generated `.apk` package from our buildsystem, but that's probably job for someone who wants it really badly :wink:

**Comment by digetx** [comment]
Kernel image itself indeed doesn't use libc. Are you asking about automating the `.apk` packaging, like @okias suggested, or something else?

**Comment by antonialoytorrens** [comment]
> Kernel image itself indeed doesn't use libc. Are you asking about automating the `.apk` packaging, like @okias suggested, or something else?

Yes, it would be great to automate the `.apk` packaging.

**Comment by antonialoytorrens** [comment]
> sadly it only works, when you don't change modules or version (which change dependency on modules version).

Oh, maybe that's the reason that it does not work straightforward for me on PostmarketOS.
