### ISSUE TITLE
ASoC: tegra: event based gpio control does not work

### ISSUE THREAD

**Issue by clamor-s** [grate-driver/linux#130]
https://github.com/grate-driver/linux/blob/0a40673c09e4165b515087a7a48a4687086061e3/sound/soc/tegra/tegra_asoc_machine.c#L79-L108

I am binding here https://github.com/clamor-s/linux/blob/p895/arch/arm/boot/dts/tegra30-lge-p895.dts#L1825-L1826 gpios, required for mics to work. If I just bind them as hogs everything is fine, but once I bind them inside tegra_asoc both mics fail.

**Comment by digetx** [comment]
You don't have `Mic Jack` and `Int Mic` in `nvidia,audio-routing`. DTB checker should tell you about the error.

**Comment by clamor-s** [comment]
So I need to route audio via those in dts? Isn't enabling those in alsa ucm enough?

**Comment by digetx** [comment]
Although, the DT seems okay. There are no event handlers set up for `Internal Mic 1` and `Internal Mic 2` in the machine driver.

You could either add `tegra_machine_event()` for `Internal Mic 1` and `Internal Mic 2` or use `Mic Jack` and `Int Mic` in the routing instead of `Internal Mic 1/2`.

**Comment by clamor-s** [comment]
I would like to, but I have too much audio devices to handle since it is a phone. I will add egra_machine_event() if you do not mind.

**Comment by digetx** [comment]
The problem with `Internal Mic 1/2` that you can't tell which one is internal or external mic. I assume you'll need to use a custom `machine->asoc->dapm_event()` handler in this case.

**Comment by digetx** [comment]
Maybe adding new `nvidia,int-mic1-en-gpios` `nvidia,int-mic2-en-gpios` won't be a bad solution.

**Comment by digetx** [comment]
I'm not sure what are those `Internal Mic 1/2`, it looks like you have three mics. Perhaps one is `noise cancellation`?

**Comment by clamor-s** [comment]
yes, mic2 is for noise cancellation

**Comment by clamor-s** [comment]
Adding tegra_machine_event worked perfectly
