### ISSUE TITLE
Fixup for kernel 6.1x and PCI patch change

### ISSUE THREAD

**Issue by kwizart** [grate-driver/linux#133]
For some reason I cannot submit a PR on grate when my kernel is not forked from it.
NVM.

leds: isa2000: https://github.com/kwizart/linux/commit/becb07b731e0ed0cec58a623b8033de774560476
revert pci: https://github.com/kwizart/linux/commit/51041c958367c835f5c1ea7e59c113cf4f84eda8
replaced by : https://github.com/kwizart/linux/commit/1d37a5dac4b66f9388c73df1b7f5b772ed05f76f

Please squash as needed.
Signed-off-by: Nicolas Chauvet <kwizart@gmail.com>

**Comment by digetx** [comment]
I applied patches locally and will push them out after fixing the recent linux-next boot regression.

**Comment by digetx** [comment]
Done
