### ISSUE TITLE
Crash in cpuidle lp2 suspend on Ouya 

### ISSUE THREAD

**Issue by Decatf** [grate-driver/linux#2]
I'm working on the Ouya Console using the current master (5.0-rc5) branch of this kernel. The device crashes in the cpuidle lp2 state.  

I don't have a serial debugger set up. I am using the android ram console driver. It isn't very reliable way to get kernel logs. The ram console logs are usually corrupted for this crash.  

I was able to resolve the crash by moving the `call_firmware_op(prepare_idle, TF_PM_MODE_LP2)` farther down the suspend path.   

https://github.com/Decatf/linux/commit/3fee4a56288762052ccf9f6727d9442218f9f1f5

**Comment by digetx** [comment]
Hello, @Decatf! That's an interesting observation. At quick glance your change matches more closely to what downstream kernel does, seems the exact match will be to invoke the firmware call after L2 cache disabling. I'll check how the change works on Nexus 7 and incorporate it into the patch if everything will be fine. 

BTW, this is a good timing to fix the last firmware itches as I was going to send out the latest version of TF-support patches to upstream around Monday. Hopefully we'll manage to upstream them this time with some help from @thierryreding.

**Comment by Decatf** [comment]
I thought it made sense to run the cache operations just before disabling it. I've tested the firmware op after `outer_disable()` and it doesn't crash.  

Rather than creating another github issue. There is an bug with the cpufreq patches. cpufreq can work on Ouya but it needs to skip the regulator enable. The Ouya regulators are on at boot and always on. The cpufreq patch always calls regulator enable during probe which makes the device lock up.  

It works fine when `regulator_is_enabled()` is checked.
https://github.com/Decatf/linux/commit/85a251d787eff0bd19f7e306a19a01aa42f48208

**Comment by digetx** [comment]
Thanks for the testing! The TF firmware is quite finicky to HW state at the time of SMC invocation, it took me some time to figure out that it doesn't like when L2 is disabled with MMU off. Ideally firmware should be agnostic to the CPU state (especially if it's about security), but nothing is ideal in this world :)  

Regulator enabling shall be a NO-OP if regulator is always-on because regulator core enables regulator at the registration time. It's either regulator-core or regulator's driver bug. You could try to add some debug messages to the core and drivers to narrow down the offending code.

**Comment by digetx** [comment]
@Decatf, the TF change you suggested works fine on Nexus7,  the relevant patch was updated and pushed out already to grate's kernel. I'll send out patches to upstream ML shortly and will add you to the CC list, please try out the updated version of the patches and don't shy to reply with yours Tested-by if everything will work fine for the Ouya.

Also, I noticed that Nexus 7 now hangs quite easily on suspend and seems changing the CPU's suspend-freq to a 1GHz (in device tree) helps by raising the suspend-resume voltage. I'm not sure whether anything changed in kernel or I changed something in the cpufreq driver and forgot already... just keep that in mind if you'll experience some odd hangs on suspend.

**Comment by digetx** [comment]
@Decatf have you resolved the regulator's bug? I removed the regulators enabling and made some other minor changes to the driver, let me know if it works for you.

**Comment by digetx** [comment]
Turned out that the current kernel base has some bug in block subsystem and only works over NFS, I'll let you know once it is fixed.

**Comment by Decatf** [comment]
> have you resolved the regulator's bug?  

I think it might be stuck in a loop in the function `regulator_balance_voltage`. The `regulator_enable` function calls into this because the cpu/core is coupled. There is a loop that tries to find the best possible voltage.

https://github.com/grate-driver/linux/blob/bc6e8e4/drivers/regulator/core.c#L3606

The system locks up after that line. That was as far I have traced the bug. I have not tried to debug it much since.

**Comment by digetx** [comment]
Oh, that's not good. Although I'm planning to extend the regulators API with a custom voltage balancer for Tegra soonish, hence bypassing that code.

**Comment by Decatf** [comment]
I was wrong. It isn't the regulator framework. The minimum core voltage has to be 1.1v otherwise the device hangs. The `regulator_balance_voltage` function takes a few iterations until it tries a min voltage below that.

**Comment by digetx** [comment]
I pushed a new version that uses custom voltage balancer. Please give it a try.

**Comment by Decatf** [comment]
Is there a constraint that the difference between cpu and core voltage should not be greater 170mV? On Galaxy Tab 10.1 this constraint does not hold.

This is the regulator values at 216 Mhz cpu.
```
$ cat /sys/kernel/debug/regulator/regulator_summary
 regulator                      use open bypass  opmode voltage current     min     max
---------------------------------------------------------------------------------------
 regulator-dummy                  3   11      0 unknown     0mV     0mA     0mV     0mV 
    serial0-0                     1                                 0mA     0mV     0mV
    serial0-0                     1                                 0mA     0mV     0mV
    6-000c                        0                                 0mA     0mV     0mV
    6-000c                        0                                 0mA     0mV     0mV
    8-0068                        0                                 0mA     0mV     0mV
    8-0068                        0                                 0mA     0mV     0mV
    2-001b                        0                                 0mA     0mV     0mV
    2-001b                        0                                 0mA     0mV     0mV
    2-001b                        0                                 0mA     0mV     0mV
    2-001b                        0                                 0mA     0mV     0mV
    2-001b                        0                                 0mA     0mV     0mV
 vdd_3v3                          7    8      0 unknown  3300mV     0mA  3300mV  3300mV 
    vdd_sys                       5    5      0 unknown  3300mV     0mA     0mV     0mV 
       vdd_core                   1    0      0 unknown  1200mV     0mA   725mV  1500mV 
       vdd_cpu                    1    1      0 unknown   750mV     0mA   725mV  1500mV 
          cpu0                    0                                 0mA   750mV  1125mV
       vdd_sm2                    2    2      0 unknown  1800mV     0mA  1800mV  1800mV 
          REG-LDO_0               0    0      0 unknown  1200mV     0mA     0mV     0mV 
          vdd_ldo1                1    0      0 unknown  1100mV     0mA  1100mV  1100mV 
       vdd_ldo5                   0    0      0 unknown  2850mV     0mA  2850mV  2850mV 
       vdd_rtc_out                1    0      0 unknown  3300mV     0mA  3300mV  3300mV 
    vdd_rtc                       1    0      0 unknown  1200mV     0mA   725mV  1500mV 
    vdd_ldo3                      1    0      0 unknown  3300mV     0mA  3300mV  3300mV 
    vdd_ldo4                      1    0      0 unknown  1800mV     0mA  1800mV  1800mV 
    vdd_ldo6                      3    3      0 unknown  3300mV     0mA  3300mV  3300mV 
       p4wifi-usb                 0                                 0mA     0mV     0mV
       c5000000.usb-phy           1                                 0mA     0mV     0mV
       3-004c                     1                                 0mA     0mV     0mV
    vdd_ldo7                      0    0      0 unknown  3300mV     0mA  3300mV  3300mV 
    vdd_ldo8                      0    0      0 unknown  1800mV     0mA  1800mV  1800mV 
    vdd_ldo9                      1    0      0 unknown  2850mV     0mA  2850mV  2850mV 
 LDO1                             0    1      0 unknown  3000mV     0mA     0mV     0mV 
    2-001b                        0                                 0mA     0mV     0mV
 LDO2                             0    1      0 unknown  1000mV     0mA     0mV     0mV 
    2-001b                        0                                 0mA     0mV     0mV
```

**Comment by digetx** [comment]
The 170mV voltage max-spread constraint is for the CORE and RTC regulators. For CPU the constraint is that CORE and RTC regulators should be at least 120mV higher than the CPU. 

The summary looks good to me, thank you very much for the testing. I'll prepare patches for upstream, will see what maintainers will say about it all.

**Comment by digetx** [comment]
Hello, @Decatf! I see that you have EMC timings table in the device-tree for the Galaxy Tab (although the definition misses the ram-code), will be great if you could try the new Tegra20 devfreq driver on yours device. You'll need to:

1. pull the recent grate-kernel updates
2. correct the device-tree timings table by adding the ram-code
3. enable CONFIG_ARM_TEGRA20_DEVFREQ in the kernel's config
4. use device for couple minutes
5. get the stats using `cat /sys/class/devfreq/devfreq0/trans_stat > stats1.txt`
6. put display into suspend using `xset dpms force off`
7. wait for a few seconds
8. get the stats againg using `cat /sys/class/devfreq/devfreq0/trans_stat > stats2.txt`
9. post the `stats1.txt` and `stats2.txt`

Thanks in advance!

**Comment by Decatf** [comment]
I've updated the Galaxy Tab 10.1 device tree emc timings table to use ram-code. It is in the following branch:  
https://github.com/Decatf/linux/tree/5.1-next-20190415-pmos

This is how I tested it:
```
$ mbw -t2 256
$ ubench whets dhry
$ cat /sys/class/devfreq/devfreq0/trans_stat > stats1.txt
$ xset dpms force off

# waited a few seconds

$ cat /sys/class/devfreq/devfreq0/trans_stat > stats2.txt
```
https://github.com/raas/mbw
https://github.com/kdlucas/byte-unixbench

Here are the results:
```
$ cat stats1.txt 
     From  :   To
           :  50000000 100000000 150000000 300000000 600000000   time(ms)
   50000000:         0         0         0         0         0         0
  100000000:         0         0         0         0         0         0
  150000000:         0         0         0         0         0         0
* 300000000:         0         0         0         0        22    565730
  600000000:         0         0         0        23         0     87100
Total transition : 45
```

```
$ cat stats2.txt 
     From  :   To
           :  50000000 100000000 150000000 300000000 600000000   time(ms)
*  50000000:         0         0         0         0         0     18340
  100000000:         0         0         0         0         0         0
  150000000:         0         0         0         0         0         0
  300000000:         0         0         0         0        36    610080
  600000000:         1         0         0        36         0    110180
Total transition : 73
```

**Comment by digetx** [comment]
@Decatf, thank you very much! The results are absolutely correct, very nice :+1:

**Comment by digetx** [comment]
I like this memory benchmarking utility https://github.com/ssvb/tinymembench, just in case if you haven't heard about it before.

BTW, could you please check that the freq stays at 600000000 while memory benchmark is running? (at least most of the time)

**Comment by Decatf** [comment]
The frequency stays at 600Mhz while most memory benchmarks are running. With tinymembench "Memory latency test" the frequency is at 50Mhz for smaller block sizes.  

For every other benchmark of mbw and tinymembench it is at 600Mhz.

**Comment by digetx** [comment]
Awesome, thank you very much again!

**Comment by digetx** [comment]
Oh, this issue is getting referenced unintendently. I think everything is resolved here already and it should be fine to close this issue now. Please let me know otherwise!

There is some progress in regards to upstreaming of CPUFreq and EMC bits, although it goes slower than it possible could.
