### ISSUE TITLE
tf300t 

### ISSUE THREAD

**Issue by hedmo** [grate-driver/linux#21]
hi at the moment i have a working grate-kernel that makes it in to X. but i have no dock functions so i cannot do anything with it . i have set all *_ASUSEC i did find with no go.
thanks for the grate work .

**Comment by clamor95** [comment]
@hedmo you tell that dock is not recognized and touchpad/keyboard do not work?

If so, join postmarketOS on Transformer group in Telegram/Matrix. There other transformer users can help you.

**Comment by hedmo** [comment]
> @hedmo you tell that dock is not recognized and touchpad/keyboard do not work?
> 
> If so, join postmarketOS on Transformer group in Telegram/Matrix. There other transformer users can help you.

@clamor95  yes i think so.but i Will check out postmarketOS on matrx. Thanks.

**Comment by clamor95** [comment]
@digetx Issue was related to userspace. Currently fixed. You may close this issue.

**Comment by digetx** [comment]
Thanks, good to know that you resolved the problem.
