### ISSUE TITLE
transformer device tree

### ISSUE THREAD

**Issue by e2002e** [grate-driver/linux#6]
Hi, when trying to compile a kernel for my nexus 7 tilapia, since I don't really know how to target architectures, transformer dtsi is included and yields that error:

Error: arch/arm/boot/dts/tegra30-asus-transformer-common.dtsi:408.5-6 syntax error
FATAL ERROR: Unable to parse input tree
make[1]: *** [scripts/Makefile.lib:313: arch/arm/boot/dts/tegra30-asus-tf201.dtb] Error 1
make: *** [Makefile:1308: dtbs] Error 2

When opening the file tegra30-asus-transformer-common.dtsi the 'errors' to correct are line 408, replace the last coma (,) with a semi-column (;).
Another error in the same file about line 1267 is the definition of usb-phy@7d008000 lacking a semi-column at the end.
Once this is fixed there is still an error at line 322, the error points to the closing of the comment.
I believe that you cannot use comments imbrication, here you comment out some code and inside it there is /*Elpida 1GB EDB8132B2MA-8D-F lpDDR2*/, using "//"  instead makes the true error pop out, which is: `arch/arm/boot/dts/tegra30-asus-tf201.dts:334.4-26 Properties must precede subnodes`.
So putting the property "nvidia,ram-code = <2>;" inside of the following subnode does fix the errors.
I'm not aware though if that's is the correct place for this property, and won't since I don't own a transfomer device. Cheers.

**Comment by digetx** [comment]
Hello @e2002e,

This compilation issue should be already fixed, please try to re-fetch the latest git master.

**Comment by e2002e** [comment]
I see the latest commit is 20hours ago and I cloned the repository about 5 hours ago.
`git pull` says 'up to date'  
I'm certain this is not fixed yet.

**Comment by okias** [comment]
Do git fetch & git reset for sure, when doing force updates, first commit can be even older than previously

**Comment by digetx** [comment]
Okay, I missed to squash the fixup change on rebase. @e2002e, should be fixed now, please try the latest git update.

**Comment by e2002e** [comment]
Ok this was what you thought. No errors here.

**Comment by digetx** [comment]
Awesome, thank you for the report! Please let us know if you'll spot anything else.
