### ISSUE TITLE
Running android.

### ISSUE THREAD

**Issue by e2002e** [grate-driver/linux#7]
Is it possible to run Android with this kernel ?
I would like to run marshmallow from unlegacy android, but I would be glad with the lollipop stock rom also.
What is the requirement to make this work ? I can see that many of the options that are present in the kernels from these OS are not recognized here. For instance BCMDHD_FW_PATH will not be added to the final config.
What I was able to do so far is booting a zImage, using the configuration named tegra_defconfig. Packing it with a ramdisk from LP or MM will produce a kernel panic.
I'd like to find out the exact configuration that is needed to boot these systems, if possible.
Thanks in advance.

**Comment by digetx** [comment]
Android won't work out-of-the-box with this kernel. You'll need to port downstream drivers + Android specific patches. It is doable, but this is quite a lot of work.

See https://github.com/digetx/picasso_upstream_support and https://github.com/digetx/picasso-kernel for an example. Note that it's for Tegra20, the Tegra30 bits may need some extra work. I switched away from Android to a proper Linux on Tegra devices few years ago, so those repos are a bit outdated in comparison to the latest kernel version. Sometime ago I was helping to port video driver to a newer kernel version and http://ftp.redsleeve.org/pub/tmp/004-tegra-downstream-video-driver.patch should contain some fixes needed for 4.8+ kernel.

BCMDHD is custom WiFi driver that is not present in upstream kernel. Brcmfmac is a generic driver that upstream uses.

For a working ramdisk you'll need to reduce zImage size by compiling most of the drivers as a loadable kernel modules. Ramdisk is getting clobbered if kernel is bigger than a certain size, it's a known issue of the upstream kernel that hasn't been resolved yet.

**Comment by e2002e** [comment]
Thanks you for enlightening this.
When you say 'a proper linux', do you mean that you have a solution to run ubuntu or debian for instance ?
I would be more interested in working toward that.

**Comment by okias** [comment]
Well supported system on Tegra 3 in [postmarketOS](https://wiki.postmarketos.org/wiki/Nvidia_Tegra_3_(tegra30)), but generally when you compile kernel, you can run any distribution, just installation will be slightly harder (I'd like to see PureOS or Mobian running on these tables).

**Comment by e2002e** [comment]
Much thanks for that, I was missing the bottom of the iceberg.

**Comment by digetx** [comment]
In the case of Ubuntu or Debian you can download armhf rootfs, extract it to /data partition and then boot to it. Ubuntu works great on Nexus 7. Also see https://github.com/grate-driver/grate/wiki/Grate-driver.
