### ISSUE TITLE
Lenovo IdeaTab - display port/ports definition missing

### ISSUE THREAD

**Issue by okias** [grate-driver/linux#85]
we need to have port or ports defined for **tegra30-lenovo-ideatab-a2109a.dts**, can you look at it @KaiJan57 ? 

```
/home/runner/work/linux/linux/arch/arm/boot/dts/tegra30-lenovo-ideatab-a2109a.dt.yaml: display-panel: 'oneOf' conditional failed, one must be fixed:
	'port' is a required property
	'ports' is a required property
	From schema: /home/runner/work/linux/linux/Documentation/devicetree/bindings/display/panel/lvds.yaml
```

**Comment by KaiJan57** [comment]
Well, I can tell for sure that it worked without specifying the `ports` property before it was mandatory. Maybe a simple `port: true` would do? I cannot test it right now though, because I currently have no access to the device.

**Comment by okias** [comment]
I believe it working as it should, but the driver missing some required data.

**Comment by KaiJan57** [comment]
Might be true, but note that I could'nt see any error messages in kernel logs concerning this issue… I don't know whether it is incompleteness of data or whether `panel-lvds` is not the right compatible? From the documentation I have read about this device, it's not fully clear to me.

**Comment by okias** [comment]
`make dtbs_check` which verify validity of DTS files reported this :wink:

**Comment by KaiJan57** [comment]
I see. I'll give a few ideas a try as soon as I find the time and get back to the tablet.

**Comment by digetx** [comment]
IdeaTab uses legacy nvidia,panel binding. Ideally we need to add a bridge node, but we don't know what bridge uses IdeaTab. Seems adding a dummy port shouldn't hurt since legacy panel still will be used.

**Comment by okias** [comment]
since this is currently last dtbs_check warning, I'm adding dummy port for now with comment.

**Comment by okias** [comment]
should be closed by https://github.com/grate-driver/linux/pull/88
